# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20170429_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
        migrations.RemoveField(
            model_name='review',
            name='food',
        ),
        migrations.RemoveField(
            model_name='review',
            name='value',
        ),
        migrations.AddField(
            model_name='review',
            name='dValue',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='deliverySpeed',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='foodQuality',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Order'),
        ),
        migrations.AddField(
            model_name='review',
            name='qValue',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='cart', max_length=10),
        ),
    ]
