# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20170514_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
