# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20170514_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cuisine',
            field=models.CharField(choices=[('American', 'American'), ('Asian', 'Asian'), ('Indian', 'Indian'), ('Mexican', 'Mexican'), ('Italian', 'Italian')], max_length=100),
        ),
    ]
