# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20170515_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
