# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default=b'unhandled', max_length=10),
        ),
    ]
