# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_message_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='issued_by',
            new_name='source',
        ),
    ]
