# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 07:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_auto_20170517_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dValue',
            field=models.PositiveIntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5')], default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='qValue',
            field=models.PositiveIntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5')], default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
