# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170428_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='rep',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
