# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customer_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deregistered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='fired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rep',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='staff',
            name='rep',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
